Vagrant.configure(2) do |config|
	config.vm.box = "name_project" # Имя box должно быть уникально для проекта 
	
	#Скачиваем нужные BOX и применям их что бы в поседствии их не скачивать
	#CentOS 6.7 https://atlas.hashicorp.com/bento/boxes/centos-6.7/versions/2.2.7/providers/virtualbox.box "bento/centos-6.7"
	#Centos 7.2 https://atlas.hashicorp.com/bento/boxes/centos-7.2/versions/2.2.9/providers/virtualbox.box "bento/centos-7.2"
	#config.vm.box_url = "E:/server/BOX/centos-7.2.box"
	
	config.vm.box_url = "https://atlas.hashicorp.com/bento/boxes/centos-6.7/versions/2.2.7/providers/virtualbox.box"
	#config.vm.box = "bento/centos-6.7" # https://atlas.hashicorp.com/bento/boxes/centos-6.7/versions/2.2.7/providers/virtualbox.box
	
	config.vm.network "private_network", ip: "192.168.50.4"
	config.vm.network "forwarded_port", guest: 80, host: 80
	
	config.vm.synced_folder "../www", "/home/bitrix/www", type: "nfs" #Если нужна более скоростная работа с диском для этого в windows нужно установить vagrant plugin install vagrant-winnfsd
	#config.vm.synced_folder "../www", "/home/bitrix/www"
	
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
		#vb.gui = true # для запуска видео виртуалбокс
	end
	
	config.vbguest.auto_update = false
	
	config.ssh.insert_key = false
	config.vm.provision :shell, :path => "./.vagrant/update.sh"
end
