Vagrant.configure(2) do |config|
	config.vm.box = "bento/centos-6.7"
	config.vm.network "private_network", ip: "192.168.50.4"
	
	config.vm.network "forwarded_port", guest: 80, host: 80
	
	config.vm.synced_folder "../www", "/home/bitrix/www", type: "nfs"
	
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "4096"
	end
	
	config.ssh.insert_key = false
	config.vm.provision :shell, :path => "./.vagrant/bitrix-env.sh"
	config.vm.provision :shell, :path => "./.vagrant/update-env.sh"
end